### ISSUE TITLE
Clicking on branch name in script pane spins forever

### ISSUE THREAD

**Issue by nolanfu** [ags131/screeps-local#1]
<img width="269" alt="screen shot 2016-08-29 at 3 39 29 pm" src="https://cloud.githubusercontent.com/assets/153935/18069884/d7871fc8-6dfe-11e6-9ce7-22ea7776fedc.png">

If I click on "default" to manage branches, the colorful progress bar at the top of the page starts animating, but nothing ever comes of it.

**Comment by ags131** [comment]
This was a registration bug and should be fixed now.
